rule kallisto_kb:
    input:
        r1 = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/align/kallisto_kb/test/sample_r1.fastq",
        r2 = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/align/kallisto_kb/test/sample_r2.fastq"
    params:
        reference = "/data/proj/GCB_FBP/references/index/kb/linnarson/index.idx",
        t2g = "/data/proj/GCB_FBP/references/index/kb/linnarson/transcripts_to_genes.txt",
        c1 = "/data/proj/GCB_FBP/references/index/kb/linnarson/cdna_transcripts_to_capture.txt",
        c2 = "/data/proj/GCB_FBP/references/index/kb/linnarson/intron_transcripts_to_capture.txt",
        whitelist = "/data/proj/GCB_FBP/references/whitelist/10xv3_whitelist.txt",
        barcode_version = "0,0,16:0,16,27:1,0,0",
        output_folder = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/align/kallisto_kb/test/output_sample/"
    wrapper: "file://.."
