rule findmarkers:
    input:
        seurat = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/findmarkers/test/seurat_obj_red_cluster.rds",
        markers = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/findmarkers/test/MARKERS_gwen.csv"
    output:
        seurat_output = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/findmarkers/test/seurat_markers.txt",
        known_markers = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/findmarkers/test/known_markers.txt"
    wrapper: "file://.."
