rule filter_sct:
    input:
        mat = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/normalization/test/unspliced_spliced_collapsed_noempty.mtx",
        barcodes = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/normalization/test/unspliced_spliced_collapsed_noempty.barcodes.txt",
        genes = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/normalization/test/unspliced_spliced_collapsed_noempty.genes.txt"
    params:
        min_features = 200,
        max_features = 5000,
        pct_mt = 5,
        min_total = 500,
        vars_regress = "NULL"
    output: "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/normalization/test/seurat_obj.Rdata"
    wrapper: "file://.."
