rule filter_empty:
    input:
        mat = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed.mtx",
        barcodes = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed.barcodes.txt",
        genes = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed.genes.txt"
    params:
        limit = 100,
        cutoff = 0.0001
    output:
        mat_output = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed_noempty.mtx",
        barcodes_output = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed_noempty.barcodes.txt",
        genes_output = "/data/proj/GCB_FBP/repos/seurat_pipeline/steps/qc/empty_drops/test/unspliced_spliced_collapsed_noempty.genes.txt"
    wrapper: "file://.."
